// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPCaemucals.Data.Identities;

#nullable disable

namespace SPCaemucals.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240214030725_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditDay")
                        .HasColumnType("int")
                        .HasComment("เครดิต-วัน");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TitleId")
                        .HasColumnType("int")
                        .HasComment("คำนำหน้าชื่อ");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.DeliveryVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryVendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Flash"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DHL"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ไปรษณีย์ไทย"
                        });
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("CashOnDelivery")
                        .HasColumnType("bit")
                        .HasComment("เก็บเงินปลายทาง Cash on delivery");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryManId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DeliveryVendorId")
                        .HasColumnType("int");

                    b.Property<int>("ParcelStatus")
                        .HasColumnType("int");

                    b.Property<string>("SaleManId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryManId");

                    b.HasIndex("DeliveryVendorId");

                    b.HasIndex("SaleManId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.Title", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "นาย"
                        },
                        new
                        {
                            Id = 2,
                            Name = "นางสาว"
                        });
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("PostalCodeCodeId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("SubDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("PostalCodeCodeId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SubDistrictId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "SSaleRole",
                            NormalizedName = "SSALEROLE"
                        },
                        new
                        {
                            Id = "3",
                            Name = "JSaleRole",
                            NormalizedName = "JSALEROLE"
                        },
                        new
                        {
                            Id = "4",
                            Name = "RSaleRole",
                            NormalizedName = "RSALEROLE"
                        },
                        new
                        {
                            Id = "5",
                            Name = "AccountRole",
                            NormalizedName = "ACCOUNTROLE"
                        });
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            CompanyId = 1,
                            ConcurrencyStamp = "845df1f7-ed82-489d-9f00-c5e0ab249bb0",
                            Email = "admin@sw.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SW.COM",
                            NormalizedUserName = "S&P_01",
                            PasswordHash = "AQAAAAIAAYagAAAAENdz+/DvoVSwvinwmOLYBaBRm6KEXxxYPWBQsoOFokqh2ooGrqfeODeV97o8ceeFSg==",
                            PhoneNumber = "0918131505",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "S&P_01"
                        });
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyName = "S&P"
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyName = "S2P"
                        },
                        new
                        {
                            CompanyId = 3,
                            CompanyName = "Aceepta"
                        });
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ThaiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.PostalCode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubDistrictId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubDistrictId");

                    b.ToTable("PostalCodes");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Multiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(1.00m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("StandardPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("SubstituteProductId")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMeasurementId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SubstituteProductId")
                        .IsUnique()
                        .HasFilter("[SubstituteProductId] IS NOT NULL");

                    b.HasIndex("UnitOfMeasurementId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("VendorId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ProductMoveHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Change")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MoveType")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAfterChange")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBeforeChange")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProductId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ProductMoveHistories");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ThaiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            ThaiName = "กรุงเทพมหานคร"
                        },
                        new
                        {
                            Id = 11,
                            ThaiName = "สมุทรปราการ"
                        },
                        new
                        {
                            Id = 12,
                            ThaiName = "นนทบุรี"
                        },
                        new
                        {
                            Id = 13,
                            ThaiName = "ปทุมธานี"
                        },
                        new
                        {
                            Id = 14,
                            ThaiName = "พระนครศรีอยุธยา"
                        },
                        new
                        {
                            Id = 15,
                            ThaiName = "อ่างทอง"
                        },
                        new
                        {
                            Id = 16,
                            ThaiName = "ลพบุรี"
                        },
                        new
                        {
                            Id = 17,
                            ThaiName = "สิงห์บุรี"
                        },
                        new
                        {
                            Id = 18,
                            ThaiName = "ชัยนาท"
                        },
                        new
                        {
                            Id = 19,
                            ThaiName = "สระบุรี"
                        },
                        new
                        {
                            Id = 20,
                            ThaiName = "ชลบุรี"
                        },
                        new
                        {
                            Id = 21,
                            ThaiName = "ระยอง"
                        },
                        new
                        {
                            Id = 22,
                            ThaiName = "จันทบุรี"
                        },
                        new
                        {
                            Id = 23,
                            ThaiName = "ตราด"
                        },
                        new
                        {
                            Id = 24,
                            ThaiName = "ฉะเชิงเทรา"
                        },
                        new
                        {
                            Id = 25,
                            ThaiName = "ปราจีนบุรี"
                        },
                        new
                        {
                            Id = 26,
                            ThaiName = "นครนายก"
                        },
                        new
                        {
                            Id = 27,
                            ThaiName = "สระแก้ว"
                        },
                        new
                        {
                            Id = 30,
                            ThaiName = "นครราชสีมา"
                        },
                        new
                        {
                            Id = 31,
                            ThaiName = "บุรีรัมย์"
                        },
                        new
                        {
                            Id = 32,
                            ThaiName = "สุรินทร์"
                        },
                        new
                        {
                            Id = 33,
                            ThaiName = "ศรีสะเกษ"
                        },
                        new
                        {
                            Id = 34,
                            ThaiName = "อุบลราชธานี"
                        },
                        new
                        {
                            Id = 35,
                            ThaiName = "ยโสธร"
                        },
                        new
                        {
                            Id = 36,
                            ThaiName = "ชัยภูมิ"
                        },
                        new
                        {
                            Id = 37,
                            ThaiName = "อำนาจเจริญ"
                        },
                        new
                        {
                            Id = 38,
                            ThaiName = "บึงกาฬ"
                        },
                        new
                        {
                            Id = 39,
                            ThaiName = "หนองบัวลำภู"
                        },
                        new
                        {
                            Id = 40,
                            ThaiName = "ขอนแก่น"
                        },
                        new
                        {
                            Id = 41,
                            ThaiName = "อุดรธานี"
                        },
                        new
                        {
                            Id = 42,
                            ThaiName = "เลย"
                        },
                        new
                        {
                            Id = 43,
                            ThaiName = "หนองคาย"
                        },
                        new
                        {
                            Id = 44,
                            ThaiName = "มหาสารคาม"
                        },
                        new
                        {
                            Id = 45,
                            ThaiName = "ร้อยเอ็ด"
                        },
                        new
                        {
                            Id = 46,
                            ThaiName = "กาฬสินธุ์"
                        },
                        new
                        {
                            Id = 47,
                            ThaiName = "สกลนคร"
                        },
                        new
                        {
                            Id = 48,
                            ThaiName = "นครพนม"
                        },
                        new
                        {
                            Id = 49,
                            ThaiName = "มุกดาหาร"
                        },
                        new
                        {
                            Id = 50,
                            ThaiName = "เชียงใหม่"
                        },
                        new
                        {
                            Id = 51,
                            ThaiName = "ลำพูน"
                        },
                        new
                        {
                            Id = 52,
                            ThaiName = "ลำปาง"
                        },
                        new
                        {
                            Id = 53,
                            ThaiName = "อุตรดิตถ์"
                        },
                        new
                        {
                            Id = 54,
                            ThaiName = "แพร่"
                        },
                        new
                        {
                            Id = 55,
                            ThaiName = "น่าน"
                        },
                        new
                        {
                            Id = 56,
                            ThaiName = "พะเยา"
                        },
                        new
                        {
                            Id = 57,
                            ThaiName = "เชียงราย"
                        },
                        new
                        {
                            Id = 58,
                            ThaiName = "แม่ฮ่องสอน"
                        },
                        new
                        {
                            Id = 60,
                            ThaiName = "นครสวรรค์"
                        },
                        new
                        {
                            Id = 61,
                            ThaiName = "อุทัยธานี"
                        },
                        new
                        {
                            Id = 62,
                            ThaiName = "กำแพงเพชร"
                        },
                        new
                        {
                            Id = 63,
                            ThaiName = "ตาก"
                        },
                        new
                        {
                            Id = 64,
                            ThaiName = "สุโขทัย"
                        },
                        new
                        {
                            Id = 65,
                            ThaiName = "พิษณุโลก"
                        },
                        new
                        {
                            Id = 66,
                            ThaiName = "พิจิตร"
                        },
                        new
                        {
                            Id = 67,
                            ThaiName = "เพชรบูรณ์"
                        },
                        new
                        {
                            Id = 70,
                            ThaiName = "ราชบุรี"
                        },
                        new
                        {
                            Id = 71,
                            ThaiName = "กาญจนบุรี"
                        },
                        new
                        {
                            Id = 72,
                            ThaiName = "สุพรรณบุรี"
                        },
                        new
                        {
                            Id = 73,
                            ThaiName = "นครปฐม"
                        },
                        new
                        {
                            Id = 74,
                            ThaiName = "สมุทรสาคร"
                        },
                        new
                        {
                            Id = 75,
                            ThaiName = "สมุทรสงคราม"
                        },
                        new
                        {
                            Id = 76,
                            ThaiName = "เพชรบุรี"
                        },
                        new
                        {
                            Id = 77,
                            ThaiName = "ประจวบคีรีขันธ์"
                        },
                        new
                        {
                            Id = 80,
                            ThaiName = "นครศรีธรรมราช"
                        },
                        new
                        {
                            Id = 81,
                            ThaiName = "กระบี่"
                        },
                        new
                        {
                            Id = 82,
                            ThaiName = "พังงา"
                        },
                        new
                        {
                            Id = 83,
                            ThaiName = "ภูเก็ต"
                        },
                        new
                        {
                            Id = 84,
                            ThaiName = "สุราษฎร์ธานี"
                        },
                        new
                        {
                            Id = 85,
                            ThaiName = "ระนอง"
                        },
                        new
                        {
                            Id = 86,
                            ThaiName = "ชุมพร"
                        },
                        new
                        {
                            Id = 90,
                            ThaiName = "สงขลา"
                        },
                        new
                        {
                            Id = 91,
                            ThaiName = "สตูล"
                        },
                        new
                        {
                            Id = 92,
                            ThaiName = "ตรัง"
                        },
                        new
                        {
                            Id = 93,
                            ThaiName = "พัทลุง"
                        },
                        new
                        {
                            Id = 94,
                            ThaiName = "ปัตตานี"
                        },
                        new
                        {
                            Id = 95,
                            ThaiName = "ยะลา"
                        },
                        new
                        {
                            Id = 96,
                            ThaiName = "นราธิวาส"
                        });
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.SubDistrict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("ThaiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("SubDistricts");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasurements");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.Customer", b =>
                {
                    b.HasOne("SPCaemucals.Data.Identities.Title", "Title")
                        .WithMany("Customers")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Title");
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.Parcel", b =>
                {
                    b.HasOne("SPCaemucals.Data.Identities.Customer", "Customer")
                        .WithMany("Parcels")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", "ShippingCoordinator")
                        .WithMany("ShippedPackage")
                        .HasForeignKey("DeliveryManId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SPCaemucals.Data.Identities.DeliveryVendor", "DeliveryVendor")
                        .WithMany("Parcels")
                        .HasForeignKey("DeliveryVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", "SaleMan")
                        .WithMany("SoldItem")
                        .HasForeignKey("SaleManId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DeliveryVendor");

                    b.Navigation("SaleMan");

                    b.Navigation("ShippingCoordinator");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Address", b =>
                {
                    b.HasOne("SPCaemucals.Data.Identities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.District", "District")
                        .WithMany("Addresses")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.PostalCode", "PostalCode")
                        .WithMany("Addresses")
                        .HasForeignKey("PostalCodeCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.Province", "Province")
                        .WithMany("Addresses")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.SubDistrict", "SubDistrict")
                        .WithMany("Addresses")
                        .HasForeignKey("SubDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("District");

                    b.Navigation("PostalCode");

                    b.Navigation("Province");

                    b.Navigation("SubDistrict");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Category", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.District", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.PostalCode", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.SubDistrict", "SubDistrict")
                        .WithMany("PostalCodes")
                        .HasForeignKey("SubDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubDistrict");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Product", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.Product", "SubstituteProduct")
                        .WithOne()
                        .HasForeignKey("SPCaemucals.Data.Models.Product", "SubstituteProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SPCaemucals.Data.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Product")
                        .HasForeignKey("UnitOfMeasurementId");

                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SPCaemucals.Data.Models.Vendor", "Vendor")
                        .WithMany("Product")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubstituteProduct");

                    b.Navigation("UnitOfMeasurement");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ProductMoveHistory", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.Category", "Category")
                        .WithMany("ProductMoveHistories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.Product", "Product")
                        .WithMany("ProductMoveHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.RefreshToken", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.SubDistrict", b =>
                {
                    b.HasOne("SPCaemucals.Data.Models.District", "District")
                        .WithMany("SubDistricts")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.DeliveryVendor", b =>
                {
                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("SPCaemucals.Data.Identities.Title", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ShippedPackage");

                    b.Navigation("SoldItem");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Category", b =>
                {
                    b.Navigation("ProductMoveHistories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.District", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("SubDistricts");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.PostalCode", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Product", b =>
                {
                    b.Navigation("ProductMoveHistories");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Province", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.SubDistrict", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("PostalCodes");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("SPCaemucals.Data.Models.Vendor", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
